services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app


