"""Add CustomerPass model

Revision ID: 07f6f98da723
Revises: ca676548dd15
Create Date: 2025-09-28 12:16:31.032522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07f6f98da723'
down_revision: Union[str, Sequence[str], None] = 'ca676548dd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customerpass',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('pass_id', sa.Uuid(), nullable=False),
    sa.Column('device', sa.Enum('IOS', 'ANDROID', 'WEB', name='deviceenum'), nullable=False),
    sa.Column('registration_method', sa.Enum('QR', 'MANUAL', 'LINK', name='registrationmethodenum'), nullable=False),
    sa.Column('apple_serial_number', sa.String(), nullable=False),
    sa.Column('apple_authentication_token', sa.String(), nullable=False),
    sa.Column('apple_device_library_id', sa.String(), nullable=False),
    sa.Column('apple_push_token', sa.String(), nullable=False),
    sa.Column('google_id_class', sa.String(), nullable=False),
    sa.Column('google_id_object', sa.String(), nullable=False),
    sa.Column('google_wallet_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['passmodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'pass_id', name='uq_customer_pass')
    )
    op.create_index(op.f('ix_customerpass_id'), 'customerpass', ['id'], unique=False)
    op.drop_constraint(op.f('customer_email_key'), 'customer', type_='unique')
    op.alter_column('passmodel', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passmodel', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(op.f('customer_email_key'), 'customer', ['email'])
    op.drop_index(op.f('ix_customerpass_id'), table_name='customerpass')
    op.drop_table('customerpass')
    # ### end Alembic commands ###
