"""changes with CustomerPass model

Revision ID: 74551c49b4cb
Revises: 07f6f98da723
Create Date: 2025-09-30 07:01:47.359447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74551c49b4cb'
down_revision: Union[str, Sequence[str], None] = '07f6f98da723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customerpass', 'apple_serial_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customerpass', 'apple_authentication_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customerpass', 'apple_device_library_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customerpass', 'apple_push_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customerpass', 'google_id_class',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customerpass', 'google_id_object',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customerpass', 'google_wallet_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customerpass', 'google_wallet_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customerpass', 'google_id_object',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customerpass', 'google_id_class',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customerpass', 'apple_push_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customerpass', 'apple_device_library_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customerpass', 'apple_authentication_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customerpass', 'apple_serial_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
