"""add_issued_at_and_make_claimed_at_nullable_in_reward

Revision ID: c3ff45e85b1d
Revises: ee8109b73186
Create Date: 2025-10-22 12:44:12.370287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3ff45e85b1d'
down_revision: Union[str, Sequence[str], None] = 'ee8109b73186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward', sa.Column('issued_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.alter_column('reward', 'claimed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # Remove the server default after adding the column
    op.alter_column('reward', 'issued_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reward', 'claimed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('reward', 'issued_at')
    # ### end Alembic commands ###
