"""Add updated_at to passmodel

Revision ID: de4cfb9fd13a
Revises: c2f10424a415
Create Date: 2025-09-02 09:37:39.741115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4cfb9fd13a'
down_revision: Union[str, Sequence[str], None] = 'c2f10424a415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passmodel', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passmodel', 'updated_at')
    # ### end Alembic commands ###
