"""Add active_stamps and active_rewards to CustomerPass

Revision ID: ee8109b73186
Revises: 74551c49b4cb
Create Date: 2025-10-11 18:51:42.640657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8109b73186'
down_revision: Union[str, Sequence[str], None] = '74551c49b4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_pass_id', sa.Uuid(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_pass_id'], ['customerpass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_id'), 'reward', ['id'], unique=False)
    op.create_table('stamp',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_pass_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_pass_id'], ['customerpass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stamp_id'), 'stamp', ['id'], unique=False)
    
    # Add columns with default values for existing records
    op.add_column('customerpass', sa.Column('active_stamps', sa.Integer(), nullable=True))
    op.add_column('customerpass', sa.Column('active_rewards', sa.Integer(), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE customerpass SET active_stamps = 0 WHERE active_stamps IS NULL")
    op.execute("UPDATE customerpass SET active_rewards = 0 WHERE active_rewards IS NULL")
    
    # Now make the columns NOT NULL
    op.alter_column('customerpass', 'active_stamps', nullable=False)
    op.alter_column('customerpass', 'active_rewards', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customerpass', 'active_rewards')
    op.drop_column('customerpass', 'active_stamps')
    op.drop_index(op.f('ix_stamp_id'), table_name='stamp')
    op.drop_table('stamp')
    op.drop_index(op.f('ix_reward_id'), table_name='reward')
    op.drop_table('reward')
    # ### end Alembic commands ###
